yarnPath: ".yarn/releases/yarn-3.6.4.cjs"
nodeLinker: "node-modules"  # safer than PnP for Hermeto
enableGlobalCache: false
enableImmutableCache: false
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

