name: Check yarn ci
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Yarn CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn ci
